Humble release versions 2023-04-25
ros2/ros2 pull request #1418
Opened 2023-04-25 22:47 UTC by audrow

2023-04-25 22:48 UTC, audrow commented on ros2.repos
> +    version: f66485139712fc524feb72281892d111d2ad4656
This is waiting on https://github.com/ros2/rosbag2/pull/1307 to be merged in, tagged, and released.

2023-04-28 04:47 UTC, clalancette requested changes

2023-04-28 04:47 UTC, clalancette commented on ros2.repos
> +    version: 0.1.1
Hm, something is weird about https://github.com/ros2/performance_test_fixture .  In particular, it doesn't have a `humble` branch.  While it isn't directly because of this change, I suggest that we:

1. Create a humble branch on https://github.com/ros2/performance_test_fixture, branched off of 0.0.9.
2. Update https://github.com/ros/rosdistro/blob/b973a540f2a10675201206bdac51a0a2ac083c14/humble/distribution.yaml#L3738 to point to that `humble` branch.
3. Update https://github.com/ros2-gbp/performance_test_fixture-release/blob/84bbf22564a06a6b0459b52f5a68dc602e87c967/tracks.yaml#L69 to point to the humble branch.
4. Revert this back to 0.0.9 here.

@audrow Does that make sense?

2023-04-28 04:47 UTC, clalancette commented on ros2.repos
> +    version: 0.15.5
It looks like a bloom release hasn't been done for this yet, so this is currently blocked on that.

2023-04-28 15:23 UTC, audrow commented on ros2.repos
> +    version: 0.15.5
Here it is: https://github.com/ros/rosdistro/pull/37011 (already merged)

2023-04-28 15:24 UTC, audrow commented on ros2.repos
> +    version: 0.1.1
Makes sense!

2023-04-28 21:34 UTC, audrow commented on ros2.repos
> +    version: 0.1.1
> * Create a humble branch on https://github.com/ros2/performance_test_fixture, branched off of 0.0.9.

[Here](https://github.com/ros2/performance_test_fixture/tree/humble)

> * Update https://github.com/ros/rosdistro/blob/b973a540f2a10675201206bdac51a0a2ac083c14/humble/distribution.yaml#L3738 to point to that `humble` branch.

[Here](https://github.com/ros/rosdistro/pull/37080)

> * Update https://github.com/ros2-gbp/performance_test_fixture-release/blob/84bbf22564a06a6b0459b52f5a68dc602e87c967/tracks.yaml#L69 to point to the humble branch.

[Here](https://github.com/ros2-gbp/performance_test_fixture-release/pull/2)

> * Revert this back to 0.0.9 here.

Done in a82c304

---

I also updated the ros2.repos file for `humble` here: https://github.com/ros2/ros2/pull/1419

2023-04-28 21:41 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-humble-sync-and-patch-release-2023-04-28/31105/5

2023-04-29 12:36 UTC, clalancette approved these changes

2023-05-02 21:36 UTC, merged