Update versions for patch-1
ros2/ros2 pull request #1456
Opened 2023-07-14 04:52 UTC by Yadunund

Updating versions for Patch Release 1

2023-07-14 04:59 UTC, Yadunund commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19155)](http://ci.ros2.org/job/ci_linux/19155/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13724)](http://ci.ros2.org/job/ci_linux-aarch64/13724/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19894)](http://ci.ros2.org/job/ci_windows/19894/)
* RHEL-9 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=443)](https://ci.ros2.org/view/All/job/ci_linux-rhel/443/)

Will run packaging jobs after CI passes.

2023-07-14 12:43 UTC, clalancette requested changes

2023-07-14 12:43 UTC, clalancette commented on ros2.repos
> +    version: v1.3.1
So this version doesn't match what is currently released into the packages: https://github.com/ros/rosdistro/blob/d1ad9d061f4125fdaf367a864e768b1634d42a24/iron/distribution.yaml#L1373 .

Looking at the differences in `foonathan_memory_vendor` between 1.3.0 and 1.3.1, the only thing that it adds is support for QNX.  Given that, I would just leave this at 1.3.0.

2023-07-14 12:43 UTC, clalancette commented on ros2.repos
> +    version: 2.1.3
This is another place where what is released into the debians doesn't match this: https://github.com/ros/rosdistro/blob/d1ad9d061f4125fdaf367a864e768b1634d42a24/iron/distribution.yaml#L3431 .  I'll suggest  leaving this at 2.1.2 (though you could also do a new release of osrf_pycommon into `iron` if you wish).

2023-07-14 12:58 UTC, Yadunund commented on ros2.repos
> +    version: v1.3.1
Ah interesting. I was looking at the version on index.ros.org which is 1.3.1 https://index.ros.org/p/foonathan_memory_vendor/github-eProsima-foonathan_memory_vendor/#iron

I'll be mindful to look at `rosdistro` instead in the future.

2023-07-14 13:01 UTC, Yadunund commented on ros2.repos
> +    version: 2.1.3
https://github.com/ros2/ros2/pull/1456/commits/fa4de477be8e94192539ee67af1c424ea5265a8a

2023-07-14 13:28 UTC, clalancette approved these changes

2023-07-15 01:55 UTC, Yadunund commented
Packaging:
* Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=548)](https://ci.ros2.org/job/ci_packaging_linux/548/)
* Linux-aarch64 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=106)](https://ci.ros2.org/job/ci_packaging_linux-aarch64/106/)
* Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=225)](https://ci.ros2.org/job/ci_packaging_windows/225/)
* Windows Debug [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=226)](https://ci.ros2.org/job/ci_packaging_windows/226/)
* RHEL-9 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=46)](https://ci.ros2.org/job/ci_packaging_linux-rhel/46/)

2023-07-17 02:05 UTC, merged