Strawman proposal for a better default ReadMe for ROS 2 repositories.
ros2/ros2 pull request #1471
Opened 2023-08-08 18:42 UTC by kscottz

Strawman proposal for a more comprehensive README.md for most of the core ROS 2 repositories.  My goal with this readme is to quickly summarize most of the core community resources for new ROS users. 

Once we converge on a final proposal my intent is to re-use this text at the end of most of the ROS 2 repos.

2023-08-08 19:59 UTC, clalancette requested changes

2023-08-08 19:59 UTC, clalancette commented on README.md
> +* [ROSCon,](https://roscon.ros.org) our yearly developer conference.
```suggestion
* [ROSCon](https://roscon.ros.org), our yearly developer conference. 
```

2023-08-08 19:59 UTC, clalancette commented on README.md
> +* [REP-2000:](https://ros.org/reps/rep-2000.html) ROS 2 Releases and Target Platforms
```suggestion
* [REP-2000](https://ros.org/reps/rep-2000.html): ROS 2 Releases and Target Platforms
```

2023-08-08 19:59 UTC, clalancette commented on README.md
> +* [ROS 1 Wiki](https://wiki.ros.org/)
I don't think we should reference the ROS 1 wiki here; that is going to eventually go away.

```suggestion
```

2023-08-08 19:59 UTC, clalancette commented on README.md
> +* [ROS Package C++ APIs](https://docs.ros.org/en/api/)
```suggestion
* [ROS Package API reference](https://docs.ros.org/en/rolling/p/)
```

2023-08-08 19:59 UTC, clalancette commented on README.md
> +
Remove trailing whitespace.

2023-08-08 20:02 UTC, kscottz commented on README.md
> +* [ROS 1 Wiki](https://wiki.ros.org/)
I am always on the fence on this one but I'll agree in this case.

2023-08-08 20:06 UTC, kscottz commented on README.md
> +
You got it.

2023-08-08 20:25 UTC, fujitatomoya approved these changes
lgtm

2023-08-09 11:56 UTC, clalancette approved these changes

2023-09-25 05:08 UTC, gbiggs reviewed
Apart from one tiny change, I think this looks fantastic. Let's get it in all the repositories!

2023-09-25 05:08 UTC, gbiggs commented on README.md
> +# Join the [ROS](https://ros.org/) Community
```suggestion
# Join the ROS Community
```

2023-09-25 05:08 UTC, gbiggs approved these changes

2024-01-12 19:14 UTC, merged