Update ros2.repos
ros2/ros2 pull request #1484
Opened 2023-09-19 14:23 UTC by audrow

- [ ] Requires this to be merged in, tagged, and released: https://github.com/ros2/rosbag2/pull/1471

2023-09-19 16:48 UTC, clalancette requested changes
A few things:

1.  I've left inline a couple of things we should fix.
2.  We need to merge in the open PRs at https://github.com/ros/rosdistro/pulls so they match.
3.  We need to merge in https://github.com/ros2/rosbag2/pull/1471 and do a release of that.

Once those things are done, this looks good to me.

2023-09-19 16:48 UTC, clalancette commented on ros2.repos
> +    version: 0.10.4
What we have released into humble right now is 0.10.3: https://github.com/ros/rosdistro/blob/a7c3c4fb0d1bb6436a505eb10c39215d3d97688b/humble/distribution.yaml#L1175

We can resolve this either by pinning the version here to 0.10.3, or doing a new bloom release of cyclonedds into Humble.  My suggestion is that we actually just pin this to 0.10.3 since we've already had that in testing for a while, but the decision is yours.

2023-09-19 16:48 UTC, clalancette commented on ros2.repos
> +    version: 2.1.4
This is actually incorrect, at least with respect to https://github.com/ros/rosdistro/blob/a7c3c4fb0d1bb6436a505eb10c39215d3d97688b/humble/distribution.yaml#L4130 (the previous version was incorrect as well).

My suggestion here is that we pin this back to 2.0.2 to match what is in rosdistro.

2023-09-20 00:53 UTC, audrow commented on ros2.repos
> +    version: 0.10.4
I've pinned it to 0.10.3 in 1bc8293.

2023-09-20 00:53 UTC, audrow commented on ros2.repos
> +    version: 2.1.4
Done in 1bc8293.

2023-09-20 20:26 UTC, audrow commented
To see if it's the new patch or just the state of the build farm:

- Humble release: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19538)](http://ci.ros2.org/job/ci_linux/19538/)
- Humble patch release 5: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19537)](http://ci.ros2.org/job/ci_linux/19537/)

2023-09-22 17:49 UTC, audrow commented
Here's the output from my tool to check against Humble's distribution file:

```
Comparing versions for humble...
 - foonathan_memory_vendor has a version mismatch:
	1.2.0 (rosdistro)	!==	1.3.1 (ros2.repos)

Skipped the following repos:
 - system_tests

Keys for the following repos could not be matched- they probably don't have the same key in the ros2.repos file and in the rosdistro file:
 - ros_tutorials

```

2023-09-25 21:37 UTC, merged