Humble release versions 2023-11-13
ros2/ros2 pull request #1496
Opened 2023-11-13 22:18 UTC by audrow

2023-11-15 14:34 UTC, clalancette requested changes
Besides the changes I pointed out inline, we should also probably do a `tinyxml2_vendor` release.

2023-11-15 14:34 UTC, clalancette commented on ros2.repos
> +    version: 0.10.4
This one we shouldn't update unless we are also going to do a binary release of it.  For now, I think we should skip this and just keep it at 0.10.3.

2023-11-15 14:34 UTC, clalancette commented on ros2.repos
> +    version: 2.1.4
This one we should leave at 2.0.2 (it's one of the few that we don't have a dedicated "humble" branch for).

2023-11-15 14:46 UTC, audrow commented on ros2.repos
> +    version: 2.1.4
Fixed in a0b2355eb62288d47aacc0b85b4e6e704d8b6fb3.

2023-11-15 14:46 UTC, audrow commented on ros2.repos
> +    version: 0.10.4
Fixed in a0b2355eb62288d47aacc0b85b4e6e704d8b6fb3.

2023-11-15 15:04 UTC, clalancette approved these changes
This looks good to me pending resolution of the license files in CI.  I'd say let's hold off on merging this for a couple of days to see if we can resolve that.  In the meantime I'll suggest merging in the rosdistro updates so the buildfarm can start rebuilding everything.

2023-11-18 12:58 UTC, clalancette commented
So there are still a lot of failing tests on all platforms here.  I think it is worthwhile to re-run the tests from the previous ros2.repos, just to see what the differences are.

2023-11-20 14:49 UTC, clalancette commented
I think the problems still have to do with the license for RTI, even though I don't understand why.

For now, I'd say let's go ahead with the patch release even with those, and we can investigate later on.

2023-11-20 22:41 UTC, audrow commented
Here is CI with the `humble-release` branch `ros2.repos` file:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19827)](http://ci.ros2.org/job/ci_linux/19827/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14327)](http://ci.ros2.org/job/ci_linux-aarch64/14327/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20548)](http://ci.ros2.org/job/ci_windows/20548/)

2023-11-21 20:34 UTC, clalancette commented
I just pushed 0c456e33e72ed4984d486593635385ad85e51231 to this branch, which updates system_tests to the latest release.  I *believe* that will fix at least some of the warnings we are getting here.  Here is more CI to verify:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19833)](http://ci.ros2.org/job/ci_linux/19833/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14331)](http://ci.ros2.org/job/ci_linux-aarch64/14331/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20555)](http://ci.ros2.org/job/ci_windows/20555/)

2023-11-22 16:45 UTC, merged