Bump versions for Iron Patch 3
ros2/ros2 pull request #1497
Opened 2023-11-17 07:36 UTC by Yadunund

TODO:
- [ ] Check if rosbag2 needs to be bumped again: https://github.com/ros2/rosbag2/pull/1487#issuecomment-1815832034
- [ ] CI job with new ros2.repos file after PR is approved
- [ ] Packaging job after CI passes
- [ ] Tag source release

2023-11-17 13:25 UTC, clalancette requested changes
This looks good with the one exception of rosbag2.

2023-11-17 13:25 UTC, clalancette commented on ros2.repos
> +    version: 0.22.4
I think we are going to need to do a 0.22.5 release to fix up the tag here.  See https://github.com/ros2/rosbag2/pull/1487#issuecomment-1816407337

2023-11-19 16:24 UTC, Yadunund commented
CI job created using https://raw.githubusercontent.com/ros2/ros2/yadu/iron-patch-3/ros2.repos

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19818)](http://ci.ros2.org/job/ci_linux/19818/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14318)](http://ci.ros2.org/job/ci_linux-aarch64/14318/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20539)](http://ci.ros2.org/job/ci_windows/20539/)
* RHEL-9 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=515)](https://ci.ros2.org/view/All/job/ci_linux-rhel/515/)

Will run packaging jobs after CI passes.

2023-11-20 01:40 UTC, Yadunund commented on ros2.repos
> +    version: 0.22.4
https://github.com/ros2/ros2/pull/1497/commits/2797436bc78aae1ad1d78d525ee4a30e380949d7

2023-11-20 01:51 UTC, Yadunund commented
Packaging:
* Linux [![Build Status](https://ci.ros2.org/view/packaging/job/packaging_linux/3237/badge/icon)](https://ci.ros2.org/view/packaging/job/packaging_linux/3237/)
* Linux-aarch64 [![Build Status](https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/2601/badge/icon)](https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/2601/)
* Windows [![Build Status](https://ci.ros2.org/view/packaging/job/packaging_windows/3058/badge/icon)](https://ci.ros2.org/view/packaging/job/packaging_windows/3058/)
* Windows Debug [![Build Status](https://ci.ros2.org/view/packaging/job/packaging_windows_debug/2017/badge/icon)](https://ci.ros2.org/view/packaging/job/packaging_windows_debug/2017/)
* RHEL-9 [![Build Status](https://ci.ros2.org/view/packaging/job/packaging_linux-rhel/1738/badge/icon)](https://ci.ros2.org/view/packaging/job/packaging_linux-rhel/1738/)

2023-11-20 14:48 UTC, clalancette commented
The packaging jobs look good.

The CI jobs are failing for the same reason as the Humble jobs, though I actually don't fully understand what is happening.  With our new RTI license, that should be working.  We'll have to take a closer look at that, but I think we can proceed with those things failing.

2023-11-20 14:48 UTC, clalancette approved these changes

2023-11-20 15:40 UTC, merged