Humble release versions 2024-01-26
ros2/ros2 pull request #1513
Opened 2024-01-24 03:00 UTC by audrow

- [ ] Merge in https://github.com/ros2/rosbag2/pull/1551

2024-01-24 16:17 UTC, clalancette commented
> Note, this is actually patch release 7. I misremembered when creating the branch. I can change it if it'd be good to do.

Nah, not necessary.  This is a temporary branch anyway and will be deleted.

2024-01-24 16:23 UTC, clalancette requested changes

2024-01-24 16:23 UTC, clalancette commented on ros2.repos
> +    version: 0.10.4
I think it is reasonable to do this update, but in that case we should also `bloom-release` it to 0.10.4.

2024-01-24 16:23 UTC, clalancette commented on ros2.repos
> +    version: 2.1.4
Same thing here; this seems like a reasonable update, but if we are going to do this we should also do a `bloom-release` of it into Humble.

2024-01-26 13:43 UTC, clalancette commented
The version bumps look good to me, but the RHEL compile failure is odd.  Either we broke something in the CI scripts (we don't test building on RHEL-8 very often), or we broke something in the Humble code.  Either way, we should take a look and see if we can fix it.

2024-01-26 14:46 UTC, clalancette commented
> The version bumps look good to me, but the RHEL compile failure is odd. Either we broke something in the CI scripts (we don't test building on RHEL-8 very often), or we broke something in the Humble code. Either way, we should take a look and see if we can fix it.

Ah, I see what is happening.  It looks like we are installing Python 3.11 in the RHEL-8 container now, and when we do `FindPython` in CMake, we are finding that.  Because `catkin_pkg` is only installed for Python 3.6, we can't find it.

@cottsay Any ideas on what is going on here, and possible thoughts for a solution?

2024-01-26 14:54 UTC, clalancette commented
OK, one more piece of information.  It looks like mesa-libGL-devel 23.1.4 (which we explicitly install [here](https://github.com/ros2/ci/blob/403b3445ee7e7253dd6c24b042feb3ae584dce76/linux_docker_resources/Dockerfile-RHEL#L110)) now requires python3.11, which is why we end up with it installed.  Maybe we either need to not install that (though I don't know the consequences), or possibly force RHEL-8 to continue to use python3.6 for everything (I'm not sure how that would work).

2024-01-26 15:29 UTC, cottsay commented
> possibly force RHEL-8 to continue to use python3.6 for everything

I do this on Fedora all the time. There are CMake flags to do it. I'll open a PR and we'll give it a shot.

2024-01-26 18:39 UTC, cottsay commented
The magic flag is `-DPython3_EXECUTABLE:STRING=/usr/bin/python3`.

[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=562)](https://ci.ros2.org/job/ci_linux-rhel/562/)

We should consider treating this like the C++ version and setting the default CMake value somewhere central. I think we want to use the system "default" python version on pretty much all supported platforms and not necessarily the "newest" version.

Certainly not suggesting we don't provide a mechanism to override, but defaulting to system default seems appropriate, and anchoring off from whichever version provides the `python3` executable seems like a safe bet.

2024-01-29 15:09 UTC, clalancette approved these changes
With the latest fixes to CI (which I just merged), this looks good to me.  Thanks @audrow and @cottsay for looking into it.

2024-01-29 16:56 UTC, merged