Update Fast-RTPS to 2.14.2.
ros2/ros2 pull request #1574
Opened 2024-06-25 17:20 UTC by clalancette

That should match what we are going to release into Rolling binary packages.

2024-06-25 17:21 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21321)](http://ci.ros2.org/job/ci_linux/21321/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15634)](http://ci.ros2.org/job/ci_linux-aarch64/15634/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=827)](http://ci.ros2.org/job/ci_linux-rhel/827/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22050)](http://ci.ros2.org/job/ci_windows/22050/)

2024-06-25 18:32 UTC, fujitatomoya requested changes

2024-06-25 18:32 UTC, fujitatomoya commented on ros2.repos
> +    version: v2.14.2
No such branch???

```suggestion
    version: 2.14.2
```

2024-06-25 18:32 UTC, fujitatomoya commented
@clalancette i think we should take https://github.com/ros2/ros2/pull/1570 to rolling instead?

CC: @MiguelCompany

2024-06-25 18:48 UTC, clalancette commented on ros2.repos
> +    version: v2.14.2
> No such branch???

This isn't a branch, it's a tag: https://github.com/eProsima/Fast-DDS/tree/v2.14.2

2024-06-25 18:48 UTC, clalancette commented
> @clalancette i think we should take #1570 to rolling instead?

Well, that one is failing CI.  But the version we currently have released into Rolling (2.14.0) doesn't actually work at all.  So I'm hoping to make the version released into CI (via https://github.com/ros/rosdistro/pull/41796) match what is in ros2.repos, and have them both work.

2024-06-25 19:30 UTC, clalancette commented
Oof, this version is failing CI, much like #1570.  Let's see if v2.14.1 is any better.

2024-06-25 19:31 UTC, clalancette commented
Using 2.14.1:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21322)](http://ci.ros2.org/job/ci_linux/21322/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15635)](http://ci.ros2.org/job/ci_linux-aarch64/15635/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=828)](http://ci.ros2.org/job/ci_linux-rhel/828/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22051)](http://ci.ros2.org/job/ci_windows/22051/)

2024-06-26 16:48 UTC, clalancette commented
All right, it looks like 2.14.1 is much better here.  I've updated the title, this needs review.  I'll also close out https://github.com/ros/rosdistro/pull/41796, and instead release 2.14.1 there.

2024-06-26 19:32 UTC, christophebedard approved these changes
The RHEL test failure isn't new. I can't find the same Windows test failure in any recent (nightly) CI, but it seems similar to some recent failures.

2024-06-26 19:38 UTC, clalancette commented
> The RHEL test failure isn't new. I can't find the same Windows test failure in any recent (nightly) CI, but it seems similar to some recent failures.

Thanks for checking!  Yes, you are correct that both of those failures are unrelated here, and have been seen on the CI farm before.  With that, I'm going to go ahead and merge this one in, thanks for the review.

2024-06-26 19:38 UTC, merged