Jazzy patch release versions  2024-07-01
ros2/ros2 pull request #1575
Opened 2024-07-01 10:18 UTC by marcoag

First Jazzy patch release :tada: 

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21344)](http://ci.ros2.org/job/ci_linux/21344/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15659)](http://ci.ros2.org/job/ci_linux-aarch64/15659/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22083)](http://ci.ros2.org/job/ci_windows/22083/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=862)](https://ci.ros2.org/job/ci_linux-rhel/862/)

Packaging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=559)](http://ci.ros2.org/job/ci_packaging_linux/559/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=107)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/107/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=65)](http://ci.ros2.org/job/ci_packaging_windows/65/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=228)](https://ci.ros2.org/job/ci_packaging_linux-rhel/228/)

2024-07-01 19:29 UTC, clalancette requested changes
Besides what I have left inline, you might also want to consider updating cyclonedds to 0.10.5, which will include all of the latest fixes.  If you do that, don't forget to also do a `bloom-release` for it.

Finally, keep a close eye on the CI for this.  I know that Jazzy still has a number of warnings, but look out for failing tests.  If you see a bunch of failing tests related to `rmw_fastrtps`, we may have to update Fast-RTPS to 2.14.1, like we did for Rolling.

2024-07-01 19:29 UTC, clalancette commented on ros2.repos
> +    version: 2.5.1
There was a late-breaking fix that you might want to get into this patch release: https://github.com/ament/ament_cmake/pull/539 .

2024-07-02 06:24 UTC, marcoag commented
Re-running CI with `ament_cmake`  `2.5.2`:

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21351)](http://ci.ros2.org/job/ci_linux/21351/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15664)](http://ci.ros2.org/job/ci_linux-aarch64/15664/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22093)](http://ci.ros2.org/job/ci_windows/22093/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=868)](https://ci.ros2.org/job/ci_linux-rhel/868/)

2024-07-02 12:36 UTC, marcoag commented on ros2.repos
> +    version: 2.5.1
Thanks for the heads up here, released: https://github.com/ros/rosdistro/pull/41915.

2024-07-02 15:19 UTC, marcoag commented
Since there's suspicious results from the buildfarm I'll run the last release and the current patch release so we can compare and identify errors.

CI `jazzy-release` branch :
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21357)](http://ci.ros2.org/job/ci_linux/21357/)

CI `jazzy_patch_release_1` branch:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21358)](http://ci.ros2.org/job/ci_linux/21358/)

2024-07-03 04:13 UTC, marcoag commented
Ok since the `jazzy_patch_release_` job hanged running a new one with a bump on fastrtps to `2.14.1`

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21360)](http://ci.ros2.org/job/ci_linux/21360/)

2024-07-03 11:53 UTC, clalancette commented
> Ok, since the `jazzy_patch_release_1` job hanged running a new one with a bump on `Fast-DDS` to `2.14.1`

All right, it looks like that one passed, and with the same warnings as the `jazzy-release` branch.

So I think we need to release 2.14.1 into Jazzy.  Note that this *isn't* the latest tag on https://github.com/eProsima/Fast-DDS, so you'll have to manually specify it when doing the `bloom-release` for it.

Separately, it might be a good idea to release cyclonedds 0.10.5 into Jazzy as well.  That should fix most of the failing tests on Linux.

2024-07-03 15:14 UTC, marcoag commented
CI with `cyclone`  `0.10.5`:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21363)](http://ci.ros2.org/job/ci_linux/21363/)

2024-07-03 17:30 UTC, marcoag commented
The rest of CI:

* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15671)](http://ci.ros2.org/job/ci_linux-aarch64/15671/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22100)](http://ci.ros2.org/job/ci_windows/22100/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=874)](https://ci.ros2.org/job/ci_linux-rhel/874/)

2024-07-03 19:41 UTC, clalancette approved these changes
Assuming CI is green-ish (including the packaging jobs), this looks good to me!

2024-07-05 06:58 UTC, marcoag commented
Packaging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=560)](http://ci.ros2.org/job/ci_packaging_linux/560/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=108)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/108/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=229)](http://ci.ros2.org/job/ci_packaging_windows/229/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=66)](https://ci.ros2.org/job/ci_packaging_linux-rhel/66/)

2024-07-05 11:58 UTC, marcoag commented
And seem to be green-ish, with some shadows of yellow. I'll take it as good and go ahead with this delayed sync! :cry:

2024-07-05 12:00 UTC, merged

2024-07-05 12:17 UTC, marcoag commented
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=230)](http://ci.ros2.org/job/ci_packaging_windows/230/)