Bump versions
ros2/ros2 pull request #1586
Opened 2024-07-29 22:10 UTC by audrow

2024-07-29 22:11 UTC, audrow commented on ros2.repos
> -    version: v2.6.7
Should I bump here? I noticed the new patch version.

2024-07-30 05:31 UTC, MiguelCompany commented on ros2.repos
> -    version: v2.6.7
I'd say we should bump to v2.6.8, to match what we have in rosdistro. Last humble merged PR there is [this one](https://github.com/ros/rosdistro/pull/40838)

2024-07-30 12:41 UTC, clalancette requested changes

2024-07-30 12:41 UTC, clalancette commented on ros2.repos
> -    version: v2.6.7
Yes, agreed, let's make this v2.6.8

2024-07-30 14:44 UTC, audrow commented on ros2.repos
> -    version: v2.6.7
Thanks, I set it to v2.6.8.

2024-07-30 17:53 UTC, clalancette approved these changes
This looks good to me with green CI.

2024-08-07 14:21 UTC, merged