Jazzy patch release 2 versions 2024-09-19
ros2/ros2 pull request #1605
Opened 2024-09-19 08:23 UTC by marcoag

First Jazzy patch release :tada: 

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21859)](https://ci.ros2.org/job/ci_linux/21859/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16129)](https://ci.ros2.org/job/ci_linux-aarch64/16129/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22570)](https://ci.ros2.org/job/ci_windows/22570/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1365)](https://ci.ros2.org/job/ci_linux-rhel/1365/)

Packaging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=562)](https://ci.ros2.org/job/ci_packaging_linux/562/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=109)](https://ci.ros2.org/job/ci_packaging_linux-aarch64/109/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=233)](https://ci.ros2.org/job/ci_packaging_windows/233/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=67)](https://ci.ros2.org/job/ci_packaging_linux-rhel/67/)

2024-09-19 16:43 UTC, marcoag commented
The RHEL jobs and linux packaging failed with `No space left on device`, retrying:
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1368)](https://ci.ros2.org/job/ci_linux-rhel/1368/)

Packaging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=563)](https://ci.ros2.org/job/ci_packaging_linux/563/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=69)](https://ci.ros2.org/job/ci_packaging_linux-rhel/69/)

2024-09-19 18:21 UTC, marcoag commented
Last min update on rclcpp: https://github.com/ros2/rclcpp/pull/2628. Marking this as a draft so it doesn't get merge, will update once packages rebuild and versions are updated here.

2024-09-20 19:17 UTC, marcoag commented
Reruning CI and packages jobs after the [rcl and rclcpp update](https://github.com/ros2/ros2/pull/1605/commits/8b5ca119f0edbc9a5c50252623d7403bc273a44a):

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21863)](https://ci.ros2.org/job/ci_linux/21863/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16133)](https://ci.ros2.org/job/ci_linux-aarch64/16133/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22574)](https://ci.ros2.org/job/ci_windows/22574/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1370)](https://ci.ros2.org/job/ci_linux-rhel/1370/)

Packaging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=564)](https://ci.ros2.org/job/ci_packaging_linux/564/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=110)](https://ci.ros2.org/job/ci_packaging_linux-aarch64/110/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=234)](https://ci.ros2.org/job/ci_packaging_windows/234/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=70)](https://ci.ros2.org/job/ci_packaging_linux-rhel/70/)

2024-09-20 19:47 UTC, marcoag commented
Windows seemed to have some issue reaching chocolatey, rerunning:

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22575)](https://ci.ros2.org/job/ci_windows/22575/)

2024-09-21 06:06 UTC, clalancette requested changes
Besides what is inline, the CI jobs are very yellow/red.  Is that expected?

2024-09-21 06:06 UTC, clalancette commented on ros2.repos
> +    version: 6.7.2
The corresponding rosdistro PR hasn't been merged yet: https://github.com/ros/rosdistro/pull/42886 .  So we either need to merge that, or put this back to 6.7.1 and wait for that update until the next patch release.

2024-09-22 06:27 UTC, marcoag commented on ros2.repos
> +    version: 6.7.2
Thanks for the catch, merged the PR, waiting for rebuild.

2024-09-22 06:44 UTC, marcoag commented
As I mentioned the red was windows not being able to reach chocolatey packages, it seems due to some network issue. 

The linux yellow ones is a `cmake_minimum_required` warning which were there on the previous [patch](https://github.com/ros2/ros2/pull/1575).

RHEL is now throwing a couple of `no CONNEXTDDS_DIR nor NDDSHOME specified` as a warning, not sure how much we care about this but it seems tests are still passing without it.

2024-09-22 09:47 UTC, clalancette commented
> RHEL is now throwing a couple of `no CONNEXTDDS_DIR nor NDDSHOME specified` as a warning, not sure how much we care about this but it seems tests are still passing without it.

Ah, that's because we stopped installing Connext for RHEL.  We should backport https://github.com/ros2/rmw_connextdds/pull/158, but it is not critical.

> I assume even though I just updated `rcutils` in the `rosdistro` file we don't have to rerun ci and packaging jobs since they were run with the `ros2.repos` from this PR, which includes `rcutils 6.7.2`.

Yes, agreed.

2024-09-22 09:48 UTC, clalancette approved these changes

2024-09-23 21:19 UTC, merged