Humble release versions 2024-12-05
ros2/ros2 pull request #1628
Opened 2024-11-25 18:02 UTC by audrow

CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22198)](http://ci.ros2.org/job/ci_linux/22198/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16450)](http://ci.ros2.org/job/ci_linux-aarch64/16450/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22948)](http://ci.ros2.org/job/ci_windows/22948/)

Build jobs:

https://ci.ros2.org/view/packaging/job/packaging_linux/3651/
https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/2998/
https://ci.ros2.org/view/packaging/job/packaging_linux-rhel/2150/
https://ci.ros2.org/view/packaging/job/packaging_windows/3453/
https://ci.ros2.org/view/packaging/job/packaging_windows_debug/2422/

Some notes:
- I bumped `libstatistics_collector` twice accidentally (no changes the second time)
- [x] ROSbag2 needs to be released: https://github.com/ros2/rosbag2/pull/1868 https://github.com/ros/rosdistro/pull/43708

2024-11-25 19:44 UTC, clalancette requested changes
Besides rosbag2 and what is inline, we should also do a bloom-release of `osrf_pycommon` so that the version in rosdistro matches what is here (I couldn't put this comment inline because of GitHub UI limitations).

2024-11-26 22:53 UTC, audrow commented on ros2.repos
>      version: v1.3.1
Set to 1.2.0.

2024-11-26 22:54 UTC, audrow commented on ros2.repos
> +    version: 0.10.5
https://github.com/ros/rosdistro/pull/43707

2024-11-26 23:14 UTC, audrow commented on ros2.repos
>    eclipse-iceoryx/iceoryx:
- [ ] osrf_pycommon: https://github.com/ros/rosdistro/pull/43710

2024-11-26 23:14 UTC, audrow commented
> Besides rosbag2 and what is inline, we should also do a bloom-release of `osrf_pycommon` so that the version in rosdistro matches what is here (I couldn't put this comment inline because of GitHub UI limitations).
- [ ] osrf_pycommon: https://github.com/ros/rosdistro/pull/43710

2024-11-27 03:31 UTC, clalancette commented on ros2.repos
>    eclipse-iceoryx/iceoryx:
Alternatively, we could set `iceoryx` here back to 2.0.5 here, so that it matches rosdistro.

2024-11-28 00:53 UTC, clalancette approved these changes
Looks good to me with green CI/packaging jobs.

2024-12-05 19:53 UTC, merged