Jazzy patch release 2024-12-23
ros2/ros2 pull request #1638
Opened 2024-12-26 14:45 UTC by marcoag

Jazzy patch release: https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-12-23/

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22314)](https://ci.ros2.org/job/ci_linux/22314/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16576)](https://ci.ros2.org/job/ci_linux-aarch64/16576/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23105)](https://ci.ros2.org/job/ci_windows/23105/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1845)](https://ci.ros2.org/job/ci_linux-rhel/1845/)

Packaging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=565)](https://ci.ros2.org/job/ci_packaging_linux/565/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=111)](https://ci.ros2.org/job/ci_packaging_linux-aarch64/111/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=236)](https://ci.ros2.org/job/ci_packaging_windows/236/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=71)](https://ci.ros2.org/job/ci_packaging_linux-rhel/71/)

2024-12-27 11:18 UTC, marcoag commented
There seems to be a [cmake_minimum_required](https://ci.ros2.org/job/ci_windows/23105/cmake/category.-1518248354/category.-1518248354/category.-1518248354/) warning on all jobs coming from the iceoryx repo, I guess we can live with that...

2024-12-27 15:53 UTC, clalancette requested changes
Besides what is in here, I think we should also probably do a release of `rosidl_typesupport_fastrtps`.  It doesn't have a huge amount of changes, but we may as well release it with everything else.

We should also do a bloom-release of `yaml_cpp_vendor`, as that is version 9.0.0 in https://github.com/ros/rosdistro/blob/6cf5283ecc1bbdbcd95562d243482088b7965765/jazzy/distribution.yaml#L9819

Finally, as for the iceoryx warning, it looks like that was fixed in iceoryx v2.0.6.  So I'm going to suggest that we update to that version here, and also do a bloom-release of that for Jazzy.

2024-12-27 15:53 UTC, clalancette commented on ros2.repos
> +    version: 0.36.6
I see a tag for 0.36.7 in the repository, so we should update to that and merge in https://github.com/ros/rosdistro/pull/44052:

```suggestion
    version: 0.36.7
```

2024-12-27 17:34 UTC, marcoag commented on ros2.repos
> +    version: 0.36.6
Sure. It seems recent so I missed it.

2024-12-28 16:10 UTC, marcoag commented
Versions updated.

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22330)](https://ci.ros2.org/job/ci_linux/22330/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16593)](https://ci.ros2.org/job/ci_linux-aarch64/16593/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23121)](https://ci.ros2.org/job/ci_windows/23121/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1861)](https://ci.ros2.org/job/ci_linux-rhel/1861/)

Packaging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=566)](https://ci.ros2.org/job/ci_packaging_linux/566/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=112)](https://ci.ros2.org/job/ci_packaging_linux-aarch64/112/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=237)](https://ci.ros2.org/job/ci_packaging_windows/237/)
* RHEL [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-rhel&build=72)](https://ci.ros2.org/job/ci_packaging_linux-rhel/72/)

2024-12-30 13:51 UTC, clalancette approved these changes
Looks good to me, thank you for the updates!

2024-12-30 22:24 UTC, merged